// BDE Training — Hints + Explanations
// One entry per question, IN THE SAME ORDER as BDE_TRAINING_QUESTIONS.
// hint = nudge shown after wrong 1st attempt
// explanation = sentence shown when revealed (right answer or after 2nd wrong)

const BDE_TRAINING_HINTS = [

  // ---------- ANGER MANAGEMENT (1-20) ----------
  { hint: "Anger has a physical signal before it turns into words or action.", explanation: "Noticing your body's signals is the earliest moment you can interrupt the reaction and choose your response." },
  { hint: "Think about what your body does when it gets ready to fight or run.", explanation: "Anger triggers the fight-or-flight response, which clenches muscles, speeds up your heart, and tightens your chest." },
  { hint: "It's a framework about what happens before and after a reaction.", explanation: "ABC separates the trigger (A) from what you tell yourself about it (B) and the outcome (C). The B step is where most growth happens." },
  { hint: "There's a real biological reason this old advice works.", explanation: "Your initial fight-or-flight surge peaks within seconds; a pause lets your rational thinking come back online." },
  { hint: "It's a pause — not a permanent exit.", explanation: "Time-outs are temporary and meant to lower the temperature so the conversation can resume productively." },
  { hint: "Anger creates physical energy — what's a safe way to use it?", explanation: "Exercise burns off the adrenaline anger generates, without harming yourself or anyone else." },
  { hint: "Think about how people react to being accused vs. having someone share how they feel.", explanation: "Blame triggers defensiveness; describing your own experience invites listening." },
  { hint: "Look for the format: I feel [emotion] when [specific situation].", explanation: "This formula names the feeling, ties it to a behavior, and avoids global accusations like 'you always.'" },
  { hint: "A longer exhale than inhale signals safety to your body.", explanation: "Slow breathing — especially a longer exhale — activates the parasympathetic nervous system, the body's brake pedal." },
  { hint: "Emotions aren't right or wrong; behavior is.", explanation: "Anger signals something matters to you. The skill is choosing how to act on that signal." },
  { hint: "Most anger has a relational cause underneath the situation.", explanation: "Beneath most anger is feeling threatened, devalued, or ignored. Naming the underlying feeling is the first step." },
  { hint: "Think 'this will ruin everything' — even when it won't.", explanation: "Catastrophizing inflates conflicts and traps you in worst-case thinking. Naming it helps you step back to reality." },
  { hint: "Walking away is fine; ghosting is not.", explanation: "Verbalizing the pause keeps the relationship intact while giving your nervous system time to reset." },
  { hint: "Anger is a cardiovascular stressor.", explanation: "Sustained anger keeps blood pressure elevated and contributes to heart disease over time." },
  { hint: "It's about basic states that make us vulnerable.", explanation: "Before reacting, check whether you're H.A.L.T. — fixing the underlying state often dissolves the reaction." },
  { hint: "Pressure with no release valve eventually finds one.", explanation: "Unexpressed anger doesn't disappear — it leaks out indirectly or erupts later. Healthy expression beats suppression." },
  { hint: "Patterns are easier to spot when written down.", explanation: "Logging triggers and reactions reveals patterns over time so you can plan better responses." },
  { hint: "Some problems benefit from a trained outside perspective.", explanation: "Therapists and groups have tools and accountability that are hard to replicate alone." },
  { hint: "Look for the option that puts other people in danger.", explanation: "Reckless driving channels anger into something that can hurt or kill — yourself or someone else." },
  { hint: "It's primarily for YOUR benefit, not theirs.", explanation: "Forgiveness frees you from carrying the weight. It doesn't require contact, reconciliation, or excusing the wrong." },

  // ---------- POLICE INTERACTION BEST PRACTICES (21-40) ----------
  { hint: "What an officer can see, they don't have to fear.", explanation: "Officer safety is their top concern; visible hands signal you're not a threat and de-escalate immediately." },
  { hint: "First impressions set the tone for the whole encounter.", explanation: "A calm opening lowers the temperature for both of you and makes the rest of the stop go smoother." },
  { hint: "Help the officer see inside the car safely.", explanation: "Lit interior makes you and the car visible, removing a common source of officer anxiety on night stops." },
  { hint: "Officers can't see your hands inside a glove box.", explanation: "Telling them what you're about to do removes any ambiguity about whether you're reaching for something dangerous." },
  { hint: "Officers train for split-second decisions.", explanation: "Quick movements look the same whether you're grabbing your ID or a weapon — slow movement keeps the situation calm." },
  { hint: "It's protected expression.", explanation: "Federal courts hold that recording police in public is protected by the First Amendment, as long as you don't interfere." },
  { hint: "Hiding it looks suspicious; brandishing it looks confrontational.", explanation: "Open, calm recording is both legal and de-escalating — it signals documentation, not escalation." },
  { hint: "The street is not the courtroom.", explanation: "The roadside is the worst place to win an argument. Compliance keeps you safe; the court is where rights get vindicated." },
  { hint: "It's about timing, not surrender.", explanation: "Saving the fight for the proper venue (court, complaint, lawyer) preserves your physical safety and your legal case." },
  { hint: "Where can you bring evidence, witnesses, and a lawyer?", explanation: "Courts, complaints, and attorneys are designed to hold officers accountable. The street is not." },
  { hint: "Three things together: what they see, what they hear, how you move.", explanation: "These three signal non-threat across visual, auditory, and physical channels at once." },
  { hint: "It's the driver's stop — back them up by staying calm.", explanation: "Passengers escalating the encounter make it worse for the driver and themselves." },
  { hint: "You can ask questions but still need to step out.", explanation: "Officers may order you out of the car during a lawful stop (Pennsylvania v. Mimms). Refusing creates more risk." },
  { hint: "Pick one voice to focus on.", explanation: "Arguing with multiple officers escalates fast. Address the lead officer and stay respectful." },
  { hint: "Giving false info to an officer is its own offense.", explanation: "Lying to law enforcement can be charged separately and almost always makes the original situation worse." },
  { hint: "You can decline — but say it out loud.", explanation: "Stating the invocation clearly signals you're using your Fifth Amendment right, not just being uncooperative." },
  { hint: "This is THE key phrase to know.", explanation: "This question forces the encounter to be either consensual (you can leave) or detention (your rights kick in)." },
  { hint: "Your calm sets theirs.", explanation: "Children mirror caregivers; staying calm reduces their distress and helps the stop go smoothly." },
  { hint: "Surprise is the worst outcome for everyone.", explanation: "Telling the officer up front (without reaching for the firearm) removes the dangerous element of surprise." },
  { hint: "Winning the moment vs. winning the long game.", explanation: "Court is for arguments; the roadside is for compliance and de-escalation. Get home first." },

  // ---------- COMMON THINGS TO KNOW (41-60) ----------
  { hint: "Where is it safe to stop without blocking traffic?", explanation: "Right shoulder lets officers approach from the safer side, away from traffic." },
  { hint: "Communicate your intent to the officer behind you.", explanation: "Signaling and gradual slowing tells the officer you're cooperating, not fleeing." },
  { hint: "Make yourself easy to read.", explanation: "Engine off, hands visible, body still — all signal compliance and reduce officer anxiety." },
  { hint: "Three documents that prove your right to drive this car.", explanation: "Driver's license, vehicle registration, and proof of insurance are the standard documents most states require during a stop." },
  { hint: "It's a fishing question — don't take the bait.", explanation: "Officers often ask this hoping for an admission. Politely deflecting doesn't lie; it just doesn't volunteer evidence." },
  { hint: "Lying about your identity is its own crime.", explanation: "Forgetting your license is a minor violation. Lying about who you are can become a serious one." },
  { hint: "States regulate visible light transmission through windows.", explanation: "Most states have tint limits and use them as lawful basis to initiate a stop." },
  { hint: "Officers can talk to anyone, but searches need cause.", explanation: "Casual contact is fine. A search of you or your belongings needs consent, a warrant, or probable cause." },
  { hint: "Look at the word 'consensual' — both sides agreeing.", explanation: "If you haven't been detained, the encounter is consensual: you can decline to answer and walk away." },
  { hint: "Don't run, but find out your status.", explanation: "Running can give probable cause to chase. Stopping and asking your status clarifies the encounter without escalating." },
  { hint: "Private venues can set entry conditions.", explanation: "Private venues can require searches as a condition of entry. You can refuse but they can refuse to let you in." },
  { hint: "Comply with the minimum required, no more.", explanation: "Checkpoints have specific legal procedures. Comply with the basics and don't volunteer extra information or items." },
  { hint: "Implied consent laws apply when you got your license.", explanation: "By accepting a driver's license, you implicitly consented to BAC testing. Refusal usually triggers automatic suspension." },
  { hint: "Signing isn't admitting guilt.", explanation: "Signing is just a promise to appear or pay. The proper place to fight the ticket is court." },
  { hint: "It's a notice, not a confession.", explanation: "Your signature acknowledges receipt and a court date — nothing about whether you committed the offense." },
  { hint: "First Amendment cuts both ways.", explanation: "You're free to record under the First Amendment, and also free not to. Neither can be compelled." },
  { hint: "Be useful without becoming a second victim.", explanation: "Calling 911 and being a credible witness is far more valuable than intervening physically." },
  { hint: "If not detained, you're free.", explanation: "Without detention, the encounter is consensual and you can leave. Asking 'Am I free to go?' confirms your status." },
  { hint: "Most states extend the open container ban to the whole car.", explanation: "Open container laws typically apply to all occupants, not just the driver." },
  { hint: "Get out of the way, period.", explanation: "Pulling right and stopping is the universal rule, designed to give emergency vehicles a predictable path." },

  // ---------- YOUR RIGHTS (61-80) ----------
  { hint: "Protects against self-incrimination.", explanation: "The Fifth Amendment prevents the government from forcing you to testify against yourself." },
  { hint: "Protects your person, property, and effects.", explanation: "The Fourth Amendment requires warrants or probable cause for most searches and arrests." },
  { hint: "Trial rights — including counsel.", explanation: "The Sixth Amendment guarantees the right to a lawyer when you're being prosecuted criminally." },
  { hint: "Don't wait until court.", explanation: "The right to counsel kicks in early — invoke it as soon as you face custodial questioning." },
  { hint: "Both conditions must be true.", explanation: "Officers don't have to Mirandize you on every contact — only when you're in custody AND being interrogated." },
  { hint: "Miranda only affects statements, not the whole case.", explanation: "If no statements were taken during interrogation, there's nothing to suppress under Miranda — the case can still proceed." },
  { hint: "Without those three things, you can decline.", explanation: "Police need a warrant, probable cause, or your consent to search. Take away those and you can refuse." },
  { hint: "Silence can be misread as agreement.", explanation: "Saying 'I do not consent to a search' is the cleanest way to preserve your Fourth Amendment claim later." },
  { hint: "Your refusal doesn't override their independent legal basis.", explanation: "Refusal protects you when the search is consent-based; it doesn't stop a warrant or probable cause search." },
  { hint: "Just being quiet isn't enough.", explanation: "Salinas v. Texas confirmed you must actually invoke the right — silence alone can be used against you." },
  { hint: "Edwards v. Arizona — once invoked, questioning ends.", explanation: "Once you clearly ask for a lawyer, officers must stop interrogating until counsel is present." },
  { hint: "Protected speech.", explanation: "Federal courts hold that recording police in public is protected expression under the First Amendment." },
  { hint: "Virginia has no broad 'stop and identify' statute for pedestrians.", explanation: "States vary on stop-and-identify laws. In Virginia, pedestrians not lawfully detained generally don't have to provide a name." },
  { hint: "Driving is a privilege, not a right.", explanation: "Operating a vehicle is a regulated privilege; producing your license on request is part of that bargain." },
  { hint: "Higher standard than a hunch.", explanation: "Probable cause requires specific facts that would lead a reasonable person to believe a crime has occurred." },
  { hint: "Enough to investigate, not enough to arrest.", explanation: "Reasonable suspicion (Terry v. Ohio) lets officers briefly detain you to investigate, but isn't enough to arrest or search fully." },
  { hint: "Casual phrasing can carry real legal weight.", explanation: "Once you agree, you've waived your Fourth Amendment objection for that search. Be careful with casual yeses." },
  { hint: "Two answers, two very different sets of rights.", explanation: "The answer flips the encounter between consensual (you can leave) and detention (rights kick in, you must stay)." },
  { hint: "It's analyzed as an unreasonable seizure.", explanation: "Graham v. Connor: excessive force claims arise under the Fourth Amendment's reasonable seizure standard." },
  { hint: "Use the system designed for it.", explanation: "Internal affairs, civilian review boards, and civil rights lawsuits are the legal remedies for rights violations." },

  // ---------- MENTAL THERAPY / MENTAL HEALTH (81-100) ----------
  { hint: "Think of it like a gym for your mind.", explanation: "Therapy isn't only for crises. Anyone working on themselves can benefit." },
  { hint: "Psychiatrist vs. psychologist is the prescription line.", explanation: "Therapists, counselors, and psychologists provide therapy. Psychiatrists are MDs who can prescribe medication." },
  { hint: "The three things it connects are right in the name.", explanation: "Cognitive Behavioral Therapy helps you spot the cycle between thoughts, feelings, and actions — and change one to change the others." },
  { hint: "Originally developed for intense emotional swings.", explanation: "DBT teaches concrete skills for tolerating distress, regulating emotions, and improving relationships." },
  { hint: "Eye movements + processing past experiences.", explanation: "EMDR helps the brain reprocess traumatic memories so they lose their grip on the present." },
  { hint: "It takes strength, not weakness.", explanation: "Choosing to do the work is a sign of self-awareness and courage, not failure." },
  { hint: "All the listed claims are common but false.", explanation: "All three are myths. Therapy is for anyone, costs money (but sliding scales exist), and usually takes time." },
  { hint: "Three-digit number for mental health emergencies.", explanation: "988 is the U.S. Suicide & Crisis Lifeline — call or text from anywhere in the country." },
  { hint: "Look for duration AND impact on your life.", explanation: "If symptoms persist for weeks and interfere with daily function, it's worth talking to a professional." },
  { hint: "It's a structured conversation, not the couch trope.", explanation: "Talk therapy is dialogue with a trained professional aimed at understanding and change." },
  { hint: "Therapists can't share, with narrow safety-related exceptions.", explanation: "Therapists must protect privacy except when there's imminent danger or required reports (abuse, threats)." },
  { hint: "One is a medical doctor.", explanation: "Psychiatrists are MDs who can prescribe and treat with medication. Psychologists provide therapy and assessment." },
  { hint: "The basics, plus social connection, plus help-seeking.", explanation: "Self-care is the everyday foundation: rest, movement, food, connection, and asking for help when you need it." },
  { hint: "It's more than sadness — and it responds to treatment.", explanation: "Depression affects mood, energy, sleep, appetite, and thinking. It's a real medical condition and it's treatable." },
  { hint: "Everyone gets anxious; clinical anxiety is different.", explanation: "When anxiety starts interfering with work, sleep, or relationships, it's worth professional attention." },
  { hint: "Trauma comes in many forms — not just combat.", explanation: "Violence, accidents, abuse, sudden loss, witnessing harm — any of these can cause PTSD." },
  { hint: "Change is gradual, not instant.", explanation: "Therapy usually unfolds over multiple sessions. The pace depends on what you're working on." },
  { hint: "Cultural messaging about toughness plays a role.", explanation: "The 'tough it out' message keeps many men from getting help they need. Breaking the silence is a strength." },
  { hint: "Cost shouldn't be the end of the conversation.", explanation: "Community clinics, employer EAPs, hotlines, and sliding-scale providers make help accessible at almost any income." },
  { hint: "Naming the struggle is half the battle.", explanation: "Acknowledging how you feel and telling one trusted person, professional, or hotline is the most important first step." }
];
