// BDE Community Service Training — Question Bank
// 100 questions across 5 topics (20 per topic)
// Correct answer is always index 0 in the canonical order below; the quiz UI
// shuffles choices at runtime, so don't reorder choices here.

const BDE_TRAINING_QUESTIONS = [

  // ============================================================
  // TOPIC 1 — ANGER MANAGEMENT (20)
  // ============================================================
  { topic: "Anger Management", q: "What is the FIRST thing to do when you feel anger rising?",
    choices: ["Pause and notice what's happening in your body", "Tell the other person they're wrong", "Walk away without saying anything", "Vent on social media"] },
  { topic: "Anger Management", q: "Which is a common PHYSICAL warning sign of rising anger?",
    choices: ["Clenched jaw or fists, faster heartbeat, tight chest", "Feeling sleepy", "Feeling hungry", "Clearer thinking"] },
  { topic: "Anger Management", q: "The \"ABC\" model of anger refers to...",
    choices: ["Activating event, Beliefs, Consequences", "Always Be Calm", "Anger, Blame, Combat", "Acting, Breathing, Calming"] },
  { topic: "Anger Management", q: "What does \"counting to 10\" before responding actually accomplish?",
    choices: ["It gives your nervous system a moment to reset", "It distracts you from the issue forever", "It makes the other person uncomfortable", "It proves you're calm"] },
  { topic: "Anger Management", q: "A \"time-out\" in anger management means...",
    choices: ["Stepping away to calm down before continuing the conversation", "Punishing the other person", "Permanently leaving the relationship", "Going silent for days"] },
  { topic: "Anger Management", q: "Which is a HEALTHY way to release built-up anger?",
    choices: ["Physical exercise or going for a walk", "Hitting walls", "Drinking alcohol", "Driving fast"] },
  { topic: "Anger Management", q: "Why do \"I\" statements help difficult conversations?",
    choices: ["They focus on your feelings without blaming the other person", "They make the other person defensive", "They end the conversation immediately", "They sound more aggressive"] },
  { topic: "Anger Management", q: "Which is a good example of an \"I\" statement?",
    choices: ["\"I feel disrespected when meetings start without me\"", "\"You always make me mad\"", "\"You're being stupid\"", "\"Everyone thinks you're wrong\""] },
  { topic: "Anger Management", q: "Which breathing pattern can quickly calm the nervous system?",
    choices: ["Slow inhale for 4, hold for 4, slow exhale for 6+", "Hold your breath as long as possible", "Fast shallow breathing", "Breathing only through your mouth"] },
  { topic: "Anger Management", q: "Anger itself is...",
    choices: ["A normal human emotion — what you DO with it is what matters", "Always wrong", "A sign of weakness", "Only a problem for men"] },
  { topic: "Anger Management", q: "Which is a common ANGER TRIGGER?",
    choices: ["Feeling disrespected, dismissed, or unheard", "Getting a good night's sleep", "Receiving compliments", "Eating a healthy meal"] },
  { topic: "Anger Management", q: "\"Catastrophizing\" during an argument means...",
    choices: ["Making the situation seem far worse than it actually is", "Calming the other person down", "Apologizing too much", "Listening carefully"] },
  { topic: "Anger Management", q: "When you're TOO angry to talk productively, the best move is to...",
    choices: ["Say \"I need a few minutes — I'll come back to this\"", "Force the conversation now", "Walk out and never return", "Insult the person before leaving"] },
  { topic: "Anger Management", q: "Chronic, unmanaged anger has been linked to which health problem?",
    choices: ["High blood pressure and heart disease", "Improved vision", "Better sleep", "Stronger immune system"] },
  { topic: "Anger Management", q: "The HALT acronym in emotional self-awareness stands for...",
    choices: ["Hungry, Angry, Lonely, Tired — common emotional triggers", "Halt, Argue, Listen, Talk", "Help, Ask, Listen, Tell", "Hold Anger, Limit Talk"] },
  { topic: "Anger Management", q: "Suppressing anger entirely (never expressing it) tends to lead to...",
    choices: ["Resentment, passive-aggression, or eventual blowup", "Healthier relationships", "Better health overall", "Faster conflict resolution"] },
  { topic: "Anger Management", q: "A \"trigger journal\" is a tool where you...",
    choices: ["Track what events tend to set off your anger and how you responded", "Write angry letters and send them", "List people you're mad at", "Record other people's bad behavior"] },
  { topic: "Anger Management", q: "If anger is hurting your job, relationships, or health, you should...",
    choices: ["Consider speaking with a therapist or anger management group", "Tough it out alone", "Cut everyone off", "Ignore it"] },
  { topic: "Anger Management", q: "Which is NOT a healthy coping strategy for anger?",
    choices: ["Driving recklessly to \"blow off steam\"", "Walking away to cool down", "Talking with a trusted friend", "Journaling"] },
  { topic: "Anger Management", q: "Forgiveness, in the context of anger management, means...",
    choices: ["Releasing your own resentment so it doesn't keep harming YOU", "Saying what the other person did was OK", "Forgetting it ever happened", "Going back to a harmful relationship"] },

  // ============================================================
  // TOPIC 2 — POLICE INTERACTION BEST PRACTICES (20)
  // ============================================================
  { topic: "Police Interaction Best Practices", q: "When approached by police, where should your hands be?",
    choices: ["Visible — on the steering wheel if in a car, or at your sides", "In your pockets", "Behind your back", "Holding your phone up to record"] },
  { topic: "Police Interaction Best Practices", q: "Your opening words to an officer should ideally be...",
    choices: ["Calm and respectful — e.g., \"Good evening, officer\"", "\"Why are you stopping me?\"", "Aggressive", "Total silence"] },
  { topic: "Police Interaction Best Practices", q: "If pulled over at night, what helps officers feel safe approaching?",
    choices: ["Turn on your interior dome light", "Turn your headlights to bright", "Get out and walk toward their car", "Hide your hands"] },
  { topic: "Police Interaction Best Practices", q: "Before reaching for your wallet or glove compartment, you should...",
    choices: ["Tell the officer what you're about to do, then move slowly", "Just grab it quickly", "Argue first", "Hide your movements"] },
  { topic: "Police Interaction Best Practices", q: "Why are sudden movements dangerous during a police encounter?",
    choices: ["They can be misread as a threat", "They speed up the stop", "They make you appear confident", "They help officers like you more"] },
  { topic: "Police Interaction Best Practices", q: "Recording a police encounter on your phone is...",
    choices: ["Generally legal in public — do it openly, not threateningly", "Always illegal", "Only legal in a few states", "A federal crime"] },
  { topic: "Police Interaction Best Practices", q: "If you choose to record, you should...",
    choices: ["Hold the phone visibly and announce you're recording", "Hide the phone", "Tell the officer the phone is a weapon", "Block the officer's face"] },
  { topic: "Police Interaction Best Practices", q: "If officers are giving you commands, your priority should be to...",
    choices: ["Comply now, contest later (in court or with a complaint)", "Argue your case immediately", "Resist", "Run"] },
  { topic: "Police Interaction Best Practices", q: "\"Comply now, contest later\" means...",
    choices: ["Get through the encounter safely; address grievances later through legal channels", "Never push back against unfair treatment", "Always plead guilty", "Avoid lawyers"] },
  { topic: "Police Interaction Best Practices", q: "If you believe an officer is wrong, the RIGHT time to challenge it is...",
    choices: ["In court, through a complaint, or with an attorney", "Right there on the street", "By fighting back", "By running away"] },
  { topic: "Police Interaction Best Practices", q: "The safest physical posture during a stop is...",
    choices: ["Hands visible, calm voice, slow movements", "Hands in pockets, raised voice", "Turning your back to the officer", "Reaching into bags"] },
  { topic: "Police Interaction Best Practices", q: "If you're a passenger and the driver is being addressed, you should...",
    choices: ["Stay quiet unless directly asked, keep your hands visible", "Speak over the driver", "Get out of the car", "Argue with the officer"] },
  { topic: "Police Interaction Best Practices", q: "When asked to step out of the vehicle, you should...",
    choices: ["Comply calmly; you can ask \"Am I being detained?\" but still step out", "Refuse", "Drive away", "Roll the window up"] },
  { topic: "Police Interaction Best Practices", q: "If multiple officers are present, you should...",
    choices: ["Speak respectfully and follow the lead officer's instructions", "Yell at all of them", "Pick a side", "Ignore them"] },
  { topic: "Police Interaction Best Practices", q: "Lying to an officer is...",
    choices: ["Usually a crime — and it can make things worse", "Always legal", "Smart strategy", "Required by law"] },
  { topic: "Police Interaction Best Practices", q: "If you don't want to answer a question, you can say...",
    choices: ["\"I'm choosing to remain silent\" — politely and clearly", "\"Mind your business\"", "Nothing at all", "Yell at the officer"] },
  { topic: "Police Interaction Best Practices", q: "If you're unsure whether you can leave, the right question is...",
    choices: ["\"Am I being detained, or am I free to go?\"", "\"Are you done yet?\"", "\"I don't have time for this\"", "Say nothing"] },
  { topic: "Police Interaction Best Practices", q: "Children in the car during a stop should be...",
    choices: ["Told calmly to stay quiet by you", "Told to get out", "Encouraged to talk to the officer", "Hidden"] },
  { topic: "Police Interaction Best Practices", q: "If you're carrying a legally owned firearm during a traffic stop, you should...",
    choices: ["Inform the officer calmly, keep hands visible, follow their instructions", "Reach for it to show them", "Hide it", "Lie about it"] },
  { topic: "Police Interaction Best Practices", q: "The overall goal of every police interaction should be...",
    choices: ["Get home safely; address concerns through proper channels later", "Win the argument", "Prove the officer wrong", "Speed things up"] },

  // ============================================================
  // TOPIC 3 — COMMON THINGS TO KNOW: POLICE / TRAFFIC / PUBLIC (20)
  // ============================================================
  { topic: "Common Things to Know — Police, Traffic, Public", q: "At a traffic stop, you should pull over to...",
    choices: ["The right shoulder, as quickly and safely as possible", "The middle of the road", "The left lane", "Only the nearest parking lot"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "While pulling over, you should...",
    choices: ["Signal, slow down, move to the right shoulder", "Speed up to a \"safer\" spot", "Stop in the lane", "Make a U-turn"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "After stopping, you should...",
    choices: ["Turn off the engine, stay seated, hands on the wheel", "Get out of the car", "Open the trunk", "Honk"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "Drivers in most U.S. states must provide which 3 documents on request?",
    choices: ["Driver's license, vehicle registration, proof of insurance", "Birth certificate, SSN card, passport", "Credit card, ID, voter card", "Lease, bank statement, work badge"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "If asked \"Do you know why I stopped you?\", a safe response is...",
    choices: ["\"No officer, can you tell me?\" — don't volunteer admissions", "Confess everything", "\"Because you don't like me\"", "Pretend you didn't hear"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "If you don't have your license on you, you should...",
    choices: ["Tell the officer truthfully and give your real name and info", "Lie about your identity", "Drive away", "Hand over someone else's license"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "Window tint that's too dark can be...",
    choices: ["A lawful basis for a traffic stop in many states", "Always legal", "Only a federal issue", "Never enforced"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "In a public space, officers can...",
    choices: ["Approach and talk to you; you may decline a search without cause", "Search you anytime without reason", "Arrest you for walking", "Take your phone freely"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "A \"consensual encounter\" means...",
    choices: ["You're free to leave at any time and aren't required to answer questions", "You're under arrest", "You've already signed something", "You must answer everything"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "If an officer says \"Stop\", the right move is to...",
    choices: ["Stop and ask politely \"Am I being detained, or am I free to go?\"", "Run", "Argue", "Walk faster"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "At a public event with bag checks or metal detectors...",
    choices: ["You can usually refuse the search but may be denied entry", "They're illegal", "You must hand over your phone", "You must answer questions about your job"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "At a DUI checkpoint, you generally must...",
    choices: ["Roll your window down briefly and present documents on request", "Drive through quickly", "Step out immediately", "Take a breath test without question"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "Refusing a breathalyzer at a stop usually results in...",
    choices: ["Automatic license suspension under \"implied consent\" laws in most states", "Nothing", "A free pass", "A cash reward"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "If you're cited and disagree with the ticket, you should...",
    choices: ["Sign (signing is NOT an admission of guilt) and contest it in court", "Tear up the ticket", "Refuse to sign", "Yell at the officer"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "Signing a traffic ticket means...",
    choices: ["You're promising to appear in court or pay — NOT admitting guilt", "You're admitting guilt", "You waived your rights", "The case is over"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "In public, regarding recording police, you have the right to...",
    choices: ["Record openly AND refuse to record — both are protected", "Only record", "Only refuse to record", "Neither"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "If you witness a public incident, the best action is to...",
    choices: ["Call 911, observe details, give a statement if asked", "Get involved physically", "Tweet about it first", "Ignore it"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "Walking away during a CONSENSUAL encounter (no detention) is...",
    choices: ["Generally lawful — ask \"Am I free to go?\" first if unsure", "A crime", "Resisting arrest", "A federal offense"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "An open container of alcohol in a vehicle is...",
    choices: ["Illegal in most states, even for passengers", "Always legal", "Only illegal for the driver", "A federal law issue only"] },
  { topic: "Common Things to Know — Police, Traffic, Public", q: "In most states, you yield to an emergency vehicle by...",
    choices: ["Pulling to the right shoulder and stopping until it passes", "Speeding up", "Stopping in the middle lane", "Honking"] },

  // ============================================================
  // TOPIC 4 — YOUR RIGHTS WHEN STOPPED BY POLICE (20)
  // ============================================================
  { topic: "Your Rights When Stopped by Police", q: "The Fifth Amendment gives you the right to...",
    choices: ["Remain silent — to not incriminate yourself", "Speak freely", "Bear arms", "A jury trial"] },
  { topic: "Your Rights When Stopped by Police", q: "The Fourth Amendment protects you against...",
    choices: ["Unreasonable searches and seizures", "Cruel and unusual punishment", "Self-incrimination", "Slavery"] },
  { topic: "Your Rights When Stopped by Police", q: "The Sixth Amendment guarantees the right to...",
    choices: ["An attorney during criminal prosecution", "Bear arms", "Remain silent", "Refuse a search"] },
  { topic: "Your Rights When Stopped by Police", q: "You have the right to ask for an attorney...",
    choices: ["As soon as you're in custody or before answering questions", "Only after conviction", "Only on weekdays", "Never"] },
  { topic: "Your Rights When Stopped by Police", q: "Miranda rights must be read to you...",
    choices: ["Before custodial interrogation — you must BE in custody AND being questioned", "Every single time an officer talks to you", "Only on TV", "After any arrest, regardless of questioning"] },
  { topic: "Your Rights When Stopped by Police", q: "If officers don't read Miranda but don't question you, the case is...",
    choices: ["NOT automatically dismissed — Miranda only affects statements made during interrogation", "Automatically thrown out", "Automatically won", "Sent to federal court"] },
  { topic: "Your Rights When Stopped by Police", q: "You can refuse a search of your vehicle when there's...",
    choices: ["No warrant, no probable cause, and you have not given consent", "A lawyer present", "An officer present", "A passenger"] },
  { topic: "Your Rights When Stopped by Police", q: "To refuse a search, you should clearly say...",
    choices: ["\"I do not consent to a search\"", "Nothing — just stay silent", "Physically block them", "\"You can't do that\""] },
  { topic: "Your Rights When Stopped by Police", q: "Even if you refuse consent, officers can still search if they have...",
    choices: ["A warrant or probable cause", "A bad mood", "Permission from your friend", "A coin flip"] },
  { topic: "Your Rights When Stopped by Police", q: "To invoke your right to remain silent, you should...",
    choices: ["Say it out loud — \"I am invoking my right to remain silent\"", "Just stay quiet without saying anything", "Whisper it", "Nothing — silence is automatic"] },
  { topic: "Your Rights When Stopped by Police", q: "Once you ask for a lawyer, officers should...",
    choices: ["Stop questioning until your attorney is present", "Keep asking questions anyway", "Arrest you faster", "Take your phone"] },
  { topic: "Your Rights When Stopped by Police", q: "Recording the police in public is generally protected by the...",
    choices: ["First Amendment", "Second Amendment", "Third Amendment", "It is not protected"] },
  { topic: "Your Rights When Stopped by Police", q: "In Virginia, if you're not driving and not lawfully detained, are you required to give your name?",
    choices: ["Generally no — Virginia has no broad \"stop and identify\" statute (rules differ by state)", "Yes, always", "Only at night", "Only if you're sitting"] },
  { topic: "Your Rights When Stopped by Police", q: "While DRIVING, you generally must show ID (your license) on request because...",
    choices: ["Driving is a regulated privilege that requires a license", "Of the First Amendment", "Officers can demand anything from anyone", "Of random local rules"] },
  { topic: "Your Rights When Stopped by Police", q: "\"Probable cause\" means...",
    choices: ["Specific facts that would lead a reasonable person to believe a crime occurred", "Any hunch", "The officer's gut feeling", "A coin flip"] },
  { topic: "Your Rights When Stopped by Police", q: "\"Reasonable suspicion\" is...",
    choices: ["A lower standard than probable cause — enough to briefly DETAIN someone to investigate", "The same as probable cause", "Just a guess", "No legal standard at all"] },
  { topic: "Your Rights When Stopped by Police", q: "If an officer asks \"Mind if I take a look?\" and you say \"yes\" or \"go ahead\", you have...",
    choices: ["Given consent — you've waived your right to refuse for that search", "Said something meaningless", "Tricked them", "Done nothing legally"] },
  { topic: "Your Rights When Stopped by Police", q: "The phrase \"Am I being detained, or am I free to go?\" helps you...",
    choices: ["Determine whether you're legally required to stay", "Anger the officer", "Stop the stop", "Cancel a ticket"] },
  { topic: "Your Rights When Stopped by Police", q: "Excessive-force claims are protected under which amendment?",
    choices: ["Fourth Amendment (unreasonable seizures)", "First Amendment", "Tenth Amendment", "No amendment"] },
  { topic: "Your Rights When Stopped by Police", q: "If your rights were violated, the right place to address it is...",
    choices: ["Through a lawyer, internal affairs complaint, civilian review board, or civil lawsuit", "Resisting on the scene", "Social media only", "Never"] },

  // ============================================================
  // TOPIC 5 — MENTAL THERAPY / MENTAL HEALTH (20)
  // ============================================================
  { topic: "Mental Therapy / Mental Health", q: "Therapy is for...",
    choices: ["Anyone wanting to understand themselves better, manage stress, or work through challenges", "Only people in crisis", "Only women", "Only people on medication"] },
  { topic: "Mental Therapy / Mental Health", q: "A therapist is...",
    choices: ["A trained mental health professional — most don't prescribe; psychiatrists do", "Always a medical doctor who prescribes meds", "A friend", "A coach with no credentials"] },
  { topic: "Mental Therapy / Mental Health", q: "CBT (Cognitive Behavioral Therapy) focuses on...",
    choices: ["The connection between thoughts, feelings, and behaviors", "Only childhood memories", "Hypnosis", "Dreams only"] },
  { topic: "Mental Therapy / Mental Health", q: "DBT (Dialectical Behavior Therapy) is best known for helping with...",
    choices: ["Emotion regulation — originally developed for borderline personality disorder", "Anger only", "Sleep only", "Marriage counseling"] },
  { topic: "Mental Therapy / Mental Health", q: "EMDR is most commonly used to treat...",
    choices: ["Trauma and PTSD", "Career counseling", "Math problems", "Sleep issues"] },
  { topic: "Mental Therapy / Mental Health", q: "Going to therapy means you're...",
    choices: ["Doing something proactive to take care of your mental health", "Weak", "Broken", "Crazy"] },
  { topic: "Mental Therapy / Mental Health", q: "Which of these about therapy are MYTHS?",
    choices: ["All of these — \"only for crazy people,\" \"costs nothing,\" \"works in one session\"", "Only the cost one", "Only the time one", "None — they're true"] },
  { topic: "Mental Therapy / Mental Health", q: "The U.S. number for a mental health crisis is...",
    choices: ["988 (Suicide & Crisis Lifeline)", "411", "311", "211"] },
  { topic: "Mental Therapy / Mental Health", q: "Signs someone may benefit from therapy include...",
    choices: ["Persistent sadness, anxiety, sleep problems, or trouble functioning", "Always feeling great", "Getting promotions", "Liking exercise"] },
  { topic: "Mental Therapy / Mental Health", q: "\"Talk therapy\" means...",
    choices: ["Speaking with a trained professional in a confidential setting", "Lying on a couch every time", "Talking to a chatbot", "Group venting only"] },
  { topic: "Mental Therapy / Mental Health", q: "Confidentiality in therapy means...",
    choices: ["What you share is private, with narrow legal exceptions (imminent danger, abuse)", "Your therapist tells your family", "Everything is posted online", "It's shared with police automatically"] },
  { topic: "Mental Therapy / Mental Health", q: "A psychiatrist differs from a psychologist mainly because...",
    choices: ["Psychiatrists are medical doctors and can prescribe medication", "Psychologists prescribe medication", "There's no difference", "Psychiatrists don't do therapy"] },
  { topic: "Mental Therapy / Mental Health", q: "\"Self-care\" in mental health includes...",
    choices: ["Sleep, exercise, nutrition, social connection, and seeking help when needed", "Spending money", "Avoiding all stress", "Never working"] },
  { topic: "Mental Therapy / Mental Health", q: "Depression is...",
    choices: ["A medical condition affecting mood, energy, sleep, and thinking — treatable", "Just sadness", "A character weakness", "Permanent"] },
  { topic: "Mental Therapy / Mental Health", q: "Anxiety becomes a clinical concern when it...",
    choices: ["Interferes with daily life, work, or relationships", "Happens once", "Helps you study", "Feels mild"] },
  { topic: "Mental Therapy / Mental Health", q: "PTSD can result from...",
    choices: ["Any traumatic event — violence, accidents, abuse, sudden loss, witnessing harm", "Only combat", "Mild stress", "Good news"] },
  { topic: "Mental Therapy / Mental Health", q: "Therapy typically takes...",
    choices: ["Multiple sessions over weeks or months — change is gradual", "One session", "Years with no result", "A weekend"] },
  { topic: "Mental Therapy / Mental Health", q: "Men are statistically LESS likely to seek mental health help because of...",
    choices: ["Stigma, cultural \"tough it out\" messaging, and not knowing where to start", "Cost only", "Bad weather", "Being too busy"] },
  { topic: "Mental Therapy / Mental Health", q: "If you can't afford therapy, options include...",
    choices: ["Sliding-scale clinics, community mental health centers, employer EAPs, 988, support groups", "Nothing — you're out of options", "Only luxury private practice", "Self-medicate"] },
  { topic: "Mental Therapy / Mental Health", q: "The most important first step toward mental health is...",
    choices: ["Acknowledging how you feel and reaching out — to a professional, friend, or hotline", "Pretending nothing's wrong", "Avoiding everyone", "Drinking more"] }
];
